name: Build Sovereign APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev ffmpeg \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libgstreamer1.0-dev libffi-dev libssl-dev autoconf \
            automake libtool pkg-config libunwind-dev libsqlite3-dev

      - name: Build Clean APK
        run: |
          pip install --upgrade pip
          pip install "buildozer==1.5.0" "cython<3.0" virtualenv
          
          # Hapus cache total untuk memastikan Aries & Neo Engine bersih
          rm -rf .buildozer
          
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer -v android debug
        env:
          yes: y

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FEAC-ULTIMATE-SOVEREIGN-OFFICIAL
          path: bin/*.apk
